---
latitude: 45.44156
longitude: 12.33066
map_zoom: 12
name: Hotel Palazzo Giovanelli e Gran Canal
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: Santa Croce, San Stae, 2070
  street2: ''
  state: ''
  city: Venice
  country: 
  zip_code: '30135'
_hotel_id: HOT061
_root_path: http://rtexpress-qa.ttaws.com/rt
