---
latitude: 45.44156
longitude: 12.33066
map_zoom: 12
name: Hotel Palazzo Giovanelli e Gran Canal
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: Santa Croce, San Stae, 2070
  street2: ''
  state: ''
  city: Venice
  country: 
  zip_code: '30135'
_hotel_id: HOT061
_portal_id: sandbox
_root_path: http://rtexpress-qa.ttaws.com/rt
_ttweb_plugins_version: v2
default_currency: USD
default_timezone: America/New_York
__EDITABLE_FIELDS__:
  name:
    required: true
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo: Palazzo Giovanelli e Gran Canal :)
