customTemplate:
  name: "2-Col"
  editableContent:
    col1:
      default: 
        type: "html"
        content: "<p>New Content</p>"        
      settings:
        type:
          type: "select"
          options: 
            - value: html
              name: HTML
            - value: image
              name: IMAGE
        style:
          type: "select"
          options: 
            - value: ""
              name: White Background
            - value: "black"
              name: Black Background
            - value: "dark"
              name: Dark Background
            - value: "light"
              name: Light Background
            - value: "gold"
              name: Gold Background
    col2:
      default: 
        type: "html"
        content: "<p>New Content</p>"              
      settings:
        type:
          type: "select"
          options: 
            - value: html
              name: HTML
            - value: image
              name: IMAGE
        style:
          type: "select"
          options: 
            - value: ""
              name: White Background
            - value: "black"
              name: Black Background
            - value: "dark"
              name: Dark Background
            - value: "light"
              name: Light Background
            - value: "gold"
              name: Gold Background
  template: <div class="row content-panel"><div class="col-md-6 content-col content-col--{{item.col1.style}}" data-live-editable-type='{{item.col1.type}}' data-live-editable-key='col1'>{{item.col1.content}}</div><div class="col-md-6 content-col content-col--{{item.col1.style}}" data-live-editable-type='{{item.col2.type}}' data-live-editable-key='col2'>{{item.col2.content}}</div></div>
