__EDITABLE_FIELDS__:
  rich_text_items:
    type: nested
    multiple: true
    fields:
      name:
        type: string
      description:
        type: richtext
  multi_rich_text:
    type: rich_text
    multiple: true
  image:
    type: image
    multiple: true
  