---
__EDITABLE_FIELDS__:
  rich_text_items:
    type: nested
    multiple: true
    fields:
      name:
        type: string
      description:
        type: richtext
  multi_rich_text:
    type: rich_text
    multiple: true
  image:
    type: image
    multiple: true
image:
- name: Junior Suite, Canal View Image 4
  file_name: Junior Suite, Canal View Image 4
  url: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/68901_1_yankee_large.jpg"
  tags: ''
  description: ''
  date_added: 2018-04-12-092608
  file_type: image/jpeg
  width: 800
  height: 600
  file_size: 39396
  url_large: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/large_68901_1_yankee_large.jpg"
  url_medium: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/medium_68901_1_yankee_large.jpg"
  url_small: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/small_68901_1_yankee_large.jpg"
  url_xsmall: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/xsmall_68901_1_yankee_large.jpg"
  url_thumb: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/thumb_68901_1_yankee_large.jpg"
  caption: ''
  alt: Image 4
  git_file_name: _assets/image_data/Junior-Suite--Canal-View-Image-4.json
  path: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-04-12-092608/68901_1_yankee_large.jpg"
rich_text_items:
- name: '1'
  description: "<p>Test</p>"
multi_rich_text:
- "<"
- p
- ">"
- H
- e
- y
- " "
- T
- h
- e
- r
- e
- "<"
- "/"
- p
- ">"
