---
__EDITABLE_FIELDS__:
  rich_text_items:
    type: nested
    multiple: true
    fields:
      name:
        type: string
      description:
        type: richtext
  multi_rich_text:
    type: rich_text
    multiple: false
  single_image:
    type: image
  image:
    type: image
    multiple: true
image:
- url: ''
  alt: ''
  caption: ''
  description: ''
rich_text_items:
- name: '1'
  description: "<p>Test!</p>"
- description: "<p>test2</p>"
multi_rich_text:
- "<"
- p
- ">"
- T
- e
- s
- t
- "<"
- "/"
- p
- ">"
single_image:
  name: img well
  file_name: img well.jpg
  url: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/img_well.jpg"
  tags: ''
  description: ''
  date_added: 2018-06-05-111232
  file_type: image/jpeg
  width: 800
  height: 600
  file_size: 214790
  url_large: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/large_img_well.jpg"
  url_medium: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/medium_img_well.jpg"
  url_small: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/small_img_well.jpg"
  url_xsmall: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/xsmall_img_well.jpg"
  url_thumb: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/thumb_img_well.jpg"
  git_file_name: _assets/image_data/img-well.json
  path: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_158_862/media/2018-06-05-111232/img_well.jpg"
  alt: img well
  caption: ''
